### ISSUE TITLE
About input text token max_length

### ISSUE THREAD

**Issue by lyakaap** [uta-smile/TCL#11]
Great work!

I noticed max_length is set to 25 [here](https://github.com/uta-smile/TCL/blob/b6d8a962e43fe7f645b7b4d93315fce619efd055/Pretrain.py#L60), which is much smaller than 77 of CLIP.
How do you derive this setting?

**Comment by viyjy** [comment]
Hi, thanks for you interest in our paper.
This setting is determined by (1) the average sentence length of the pre-training dataset and (2) computational efficiency.
Feel free to let me know if you might have any other questions/suggestions. Thanks.

**Comment by lyakaap** [comment]
Thank you very much for your answer!
