### ISSUE TITLE
Roughly how much time does the zero-shot retrieval evaluation take?

### ISSUE THREAD

**Issue by yash0307** [uta-smile/TCL#15]
Hi,

Many thanks for the great work and releasing the code. How much time does the inference of zero-shot retrieval take? On 2 V100s, it takes around 2 hours for me on MS-COCO. Is that normal or something is potentially wrong with my setup?

Many thanks in advance.

**Comment by viyjy** [comment]
Thanks for your interest in our work. I remember that it takes about 30mins on MS-COCO. Our machine is A100 with GPU memory size=40GB. Are you using the default batch size?

**Comment by yash0307** [comment]
Yes, default batch size from the retrieval_coco config.

**Comment by yash0307** [comment]
How many A100s do you use for the evaluation?

**Comment by viyjy** [comment]
As you can see here https://github.com/uta-smile/TCL#image-text-retrieval, we are using 8 GPUs.

**Comment by yash0307** [comment]
Thanks.
