### ISSUE TITLE
Question about Data augmentation for MoCo.

### ISSUE THREAD

**Issue by celestialxevermore** [uta-smile/TCL#17]
Dear author, I feel thankful of your great masterpiece, and I really appreciate about your work these days.

Reading your paper with comprehending your code, 

I got in my mind about data augmentation.

I found that you give data augmentation on Image, then, did you do same thing on text modalities?

If it is right, then can you check out that line in code?

Thx.

**Comment by viyjy** [comment]
Hi, thanks for your interest in our paper.
No, there is not data augmentation for text input, but we follow [simCSE](https://arxiv.org/abs/2104.08821) and
consider standard dropout as minimal data augmentation for the text.

**Comment by celestialxevermore** [comment]
Thx. your reply is helpful. Hope you have good days :)
