### ISSUE TITLE
Release finetuned checkpoint

### ISSUE THREAD

**Issue by byougert** [uta-smile/TCL#2]
Hi,
First of al, thanks for your sharing code and excellent paper.
I wonder if you could provide the checkpoints finetuned on flickr and coco?

**Comment by viyjy** [comment]
Sure, I will upload them today. Thanks.

**Comment by byougert** [comment]
Wow, thanks!

**Comment by viyjy** [comment]
@byougert Hi, sorry for the late reply. Please check the [checkpoints](https://github.com/uta-smile/TCL#pre-trained-checkpoint) and feel free to let me know if you might need additional information. Thanks.
