### ISSUE TITLE
No module named 'refTools'

### ISSUE THREAD

**Issue by PeterDykas** [uta-smile/TCL#3]
Hi I am trying to reproduce the results from inside a docker container.  After installing the dependencies I hit the following error:
```Traceback (most recent call last):
  File "Pretrain.py", line 30, in <module>
    from dataset import create_dataset, create_sampler, create_loader
  File "/workspace/dataset/__init__.py", line 6, in <module>
    from dataset.caption_dataset import re_train_dataset, re_eval_dataset, pretrain_dataset
  File "/workspace/dataset/caption_dataset.py", line 12, in <module>
    from dataset.utils import pre_caption
  File "/workspace/dataset/utils.py", line 45, in <module>
    from refTools.evaluation.refEvaluation import RefEvaluation
ModuleNotFoundError: No module named 'refTools'
```

 every time when running: 

`python -m torch.distributed.launch --nproc_per_node=8 \
--use_env Pretrain.py \
--config ./configs/Pretrain.yaml \
--output_dir output/pretrain`

I have tried `pip3 install reftools` but it does not solve the issue.  Have you run into this issue before?

**Comment by viyjy** [comment]
Hi, thanks for your interest of our work. Let me double check this issue on my machine, will let you know ASAP.

**Comment by viyjy** [comment]
Hi, please download https://drive.google.com/file/d/1MNlw7LZvABMt_0dKu5b7RyzvUb1c7PKY/view?usp=sharing , then unzip it, then put it under your TCL folder. Please let me know if you might need any further information.

**Comment by PeterDykas** [comment]
That seems to have fixed the issue thank you.  If I want to run on only a subset of the pretraining data is commenting out unused datasets sufficient?

**Comment by viyjy** [comment]
Yes, just modify `train_file` in [Pretrain.yaml](https://github.com/uta-smile/TCL/blob/main/configs/Pretrain.yaml).

**Comment by PeterDykas** [comment]
Awesome thanks, I see that you listed MSCOCO 2014 as a dataset but I am going to assume it means the MSCOCO 2015 where the  captioning competition was.

**Comment by viyjy** [comment]
Please only download MSCOCO 2014 datasets from these links.
[2014 Train images [83K/13GB]](http://images.cocodataset.org/zips/train2014.zip)
[2014 Val images [41K/6GB]](http://images.cocodataset.org/zips/val2014.zip)
[2014 Test images [41K/6GB]](http://images.cocodataset.org/zips/test2014.zip)
