### ISSUE TITLE
the difference between dino loss and loss_i2i_inMod_l

### ISSUE THREAD

**Issue by liangzimei** [uta-smile/TCL#5]
hi, these two losses are both to pull the distance of global and local representation in reverso context,  is there any differences i have not got?

**Comment by viyjy** [comment]
Hi, can you explain which DINO loss? If you are talking about "Emerging Properties in Self-Supervised Vision Transformers", I didn't find a loss in this paper that pull the distance of global and local representation.

**Comment by liangzimei** [comment]
![image](https://user-images.githubusercontent.com/12395126/162425486-e9369db7-9b44-4f0f-aac9-2c06fa1c6f7f.png)
Yes, i'm talking about this paper. there is a description in section 3.1

**Comment by viyjy** [comment]
Thanks. You are correct, they are quite similar, the difference is that DINO uses images with low resolution as "local", while TCL uses patch features as "local". Our global-to-local is inspired by "Learning deep representations by mutual information estimation and maximization".

**Comment by liangzimei** [comment]
> Thanks. You are correct, they are quite similar, the difference is that DINO uses images with low resolution as "local", while TCL uses patch features as "local". Our global-to-local is inspired by "Learning deep representations by mutual information estimation and maximization".

thanks for your reply, i got it. i will close the issue~
