### ISSUE TITLE
About GPU Usage and Training Time

### ISSUE THREAD

**Issue by yangbang18** [uta-smile/TCL#6]
Hi, thanks for your great work and code sharing. 

According to config/Pretrain.yaml, the `batch_size` is set to `64` (i.e., each GPU will process 64 image-text pairs) during pretraining. I would like to know how much GPU memory will be used and how much time will be taken per epoch (on 4M dataset) under this setting. 

By the way, I have read your excellent paper but can not find the supplementary materials on the web. Could you share a link to download it? Thanks a lot.

**Comment by viyjy** [comment]
Hi, thanks for your interest in our paper.

1. The GPU memory usage is about 30GB on each GPU. We use A100 which contains 8 GPUs.
2. The training time for each epoch is about 2 hours.
3. We don't have the supplementary file. If you need anything that is clearly mentioned in the paper, just let me know. 

Thanks.
