### ISSUE TITLE
About the queue

### ISSUE THREAD

**Issue by zsmmsz99** [uta-smile/TCL#8]
Thanks for this wonderful work, i am confused about the queue size. Why is the queue size 65536. 

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by viyjy** [comment]
Hi, thanks for your interest in our paper.
We follow [MoCo](https://arxiv.org/abs/1911.05722) to set the queue size=65536. Actually, there is no specific reason for this setting.

**Comment by zsmmsz99** [comment]
Thanks a lot, i will read this paper today. Respect!
